# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tambah.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TambahKamar(object):
    def setupUi(self, TambahKamar):
        TambahKamar.setObjectName("TambahKamar")
        TambahKamar.resize(602, 398)
        TambahKamar.setStyleSheet("\n"
"     QWidget {  background-color: rgb(231,228,176);}\n"
"    QPushButton { background-color:#8b5e3c; color:white; border-radius:4px; padding:6px; }\n"
"    QLabel { color:#3e2a16; font-weight:bold; }\n"
"    QLineEdit, QTextEdit { background:white; border:1px solid #8b5e3c; }\n"
"   ")
        self.gridLayout = QtWidgets.QGridLayout(TambahKamar)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(TambahKamar)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label1 = QtWidgets.QLabel(TambahKamar)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(TambahKamar)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label2 = QtWidgets.QLabel(TambahKamar)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(TambahKamar)
        self.lineEdit.setStyleSheet("color: rgb(174, 174, 174);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 5, 1, 1, 1)
        self.input_harga = QtWidgets.QLineEdit(TambahKamar)
        self.input_harga.setObjectName("input_harga")
        self.gridLayout.addWidget(self.input_harga, 4, 1, 1, 2)
        self.btn_tambah = QtWidgets.QPushButton(TambahKamar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_tambah.setFont(font)
        self.btn_tambah.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btn_tambah.setObjectName("btn_tambah")
        self.gridLayout.addWidget(self.btn_tambah, 6, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(TambahKamar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 5, 2, 1, 1)
        self.input_stok = QtWidgets.QLineEdit(TambahKamar)
        self.input_stok.setObjectName("input_stok")
        self.gridLayout.addWidget(self.input_stok, 3, 1, 1, 2)
        self.input_deskripsi = QtWidgets.QTextEdit(TambahKamar)
        self.input_deskripsi.setObjectName("input_deskripsi")
        self.gridLayout.addWidget(self.input_deskripsi, 2, 1, 1, 2)
        self.input_nama = QtWidgets.QLineEdit(TambahKamar)
        self.input_nama.setObjectName("input_nama")
        self.gridLayout.addWidget(self.input_nama, 1, 1, 1, 2)
        self.label3 = QtWidgets.QLabel(TambahKamar)
        self.label3.setObjectName("label3")
        self.gridLayout.addWidget(self.label3, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(TambahKamar)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 3, QtCore.Qt.AlignHCenter)
        self.pushButton_2 = QtWidgets.QPushButton(TambahKamar)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 6, 2, 1, 1)

        self.retranslateUi(TambahKamar)
        QtCore.QMetaObject.connectSlotsByName(TambahKamar)

    def retranslateUi(self, TambahKamar):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("TambahKamar", "Stok:"))
        self.label1.setText(_translate("TambahKamar", "Harga:"))
        self.label_2.setText(_translate("TambahKamar", "Gambar:"))
        self.label2.setText(_translate("TambahKamar", "Nama Kamar:"))
        self.lineEdit.setText(_translate("TambahKamar", "Pilih gambar kamar"))
        self.btn_tambah.setText(_translate("TambahKamar", "Tambah"))
        self.pushButton.setText(_translate("TambahKamar", "📁 Pilih"))
        self.label3.setText(_translate("TambahKamar", "Deskripsi:"))
        self.label_3.setText(_translate("TambahKamar", "Tambah Kamar"))
        self.pushButton_2.setText(_translate("TambahKamar", "Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TambahKamar = QtWidgets.QWidget()
    ui = Ui_TambahKamar()
    ui.setupUi(TambahKamar)
    TambahKamar.show()
    sys.exit(app.exec_())
