# Form implementation generated from reading ui file 'dashboard_user.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DashboardAdmin(object):
    def setupUi(self, DashboardAdmin):
        DashboardAdmin.setObjectName("DashboardAdmin")
        DashboardAdmin.resize(782, 557)
        self.verticalLayout = QtWidgets.QVBoxLayout(DashboardAdmin)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameHeader = QtWidgets.QFrame(parent=DashboardAdmin)
        self.frameHeader.setStyleSheet("\n"
"        QFrame { background-color: rgb(174,167,126); border-radius: 10px; padding: 10px; }\n"
"        QLabel { font-size: 18pt; font-weight: bold; color: rgb(80,60,40); }\n"
"      ")
        self.frameHeader.setObjectName("frameHeader")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frameHeader)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=self.frameHeader)
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout.addWidget(self.lblTitle)
        self.verticalLayout.addWidget(self.frameHeader)
        self.tabAdmin = QtWidgets.QTabWidget(parent=DashboardAdmin)
        self.tabAdmin.setStyleSheet("\n"
"        QTabBar::tab { background-color: rgb(255,244,185); padding: 8px 20px; border-radius: 6px; margin-right: 5px; }\n"
"        QTabBar::tab:selected { background-color: rgb(200,180,120); }\n"
"\n"
"        /* Style untuk QTableWidget di tab Booking */\n"
"        QTableWidget {\n"
"          background-color: rgb(255, 255, 255);\n"
"          border: 1px solid rgb(184,182,139);\n"
"          gridline-color: rgb(200, 200, 200);\n"
"          selection-background-color: rgb(200,180,120);\n"
"        }\n"
"        QHeaderView::section {\n"
"          background-color: rgb(231,228,176);\n"
"          padding: 4px;\n"
"          border: 1px solid rgb(184,182,139);\n"
"          font-weight: bold;\n"
"        }\n"
"\n"
"        /* Style untuk tombol di tab Booking dan Payments */\n"
"        QPushButton {\n"
"          padding: 8px 15px;\n"
"          border-radius: 6px;\n"
"          font-weight: bold;\n"
"          color: white;\n"
"        }\n"
"        QPushButton#btnApproveBooking {\n"
"          background-color: rgb(80,160,80); /* Green for Approve */\n"
"          border: 1px solid rgb(60,140,60);\n"
"        }\n"
"        QPushButton#btnApproveBooking:hover {\n"
"          background-color: rgb(90,170,90);\n"
"        }\n"
"        QPushButton#btnCancelBooking {\n"
"          background-color: rgb(190,60,60); /* Red for Cancel */\n"
"          border: 1px solid rgb(170,40,40);\n"
"        }\n"
"        QPushButton#btnCancelBooking:hover {\n"
"          background-color: rgb(210,70,70);\n"
"        }\n"
"        QPushButton#btnRefreshPayments {\n"
"          background-color: rgb(100,100,180);\n"
"        }\n"
"        QPushButton#btnViewPaymentDetails {\n"
"          background-color: rgb(80,160,80);\n"
"        }\n"
"\n"
"      ")
        self.tabAdmin.setObjectName("tabAdmin")
        self.tabRooms = QtWidgets.QWidget()
        self.tabRooms.setObjectName("tabRooms")
        self.layoutRoomsMain = QtWidgets.QVBoxLayout(self.tabRooms)
        self.layoutRoomsMain.setObjectName("layoutRoomsMain")
        self.layoutRoomButtons = QtWidgets.QHBoxLayout()
        self.layoutRoomButtons.setObjectName("layoutRoomButtons")
        self.scrollAreaRooms = QtWidgets.QScrollArea(parent=self.tabRooms)
        self.scrollAreaRooms.setWidgetResizable(True)
        self.scrollAreaRooms.setObjectName("scrollAreaRooms")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 719, 1608))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.roomFrame2_11 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_11.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_11.setObjectName("roomFrame2_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.roomFrame2_11)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.roomTextCol2_11 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_11.setObjectName("roomTextCol2_11")
        self.horizontalLayout_9.addLayout(self.roomTextCol2_11)
        self.textEdit_13 = QtWidgets.QTextEdit(parent=self.roomFrame2_11)
        self.textEdit_13.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_13.setObjectName("textEdit_13")
        self.horizontalLayout_9.addWidget(self.textEdit_13)
        self.label_25 = QtWidgets.QLabel(parent=self.roomFrame2_11)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.btnPrice2_11 = QtWidgets.QPushButton(parent=self.roomFrame2_11)
        self.btnPrice2_11.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_11.setObjectName("btnPrice2_11")
        self.horizontalLayout_9.addWidget(self.btnPrice2_11)
        self.gridLayout.addWidget(self.roomFrame2_11, 7, 1, 1, 1)
        self.roomFrame2_8 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_8.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_8.setObjectName("roomFrame2_8")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.roomFrame2_8)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.roomTextCol2_8 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_8.setObjectName("roomTextCol2_8")
        self.horizontalLayout_12.addLayout(self.roomTextCol2_8)
        self.textEdit_10 = QtWidgets.QTextEdit(parent=self.roomFrame2_8)
        self.textEdit_10.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_10.setObjectName("textEdit_10")
        self.horizontalLayout_12.addWidget(self.textEdit_10)
        self.label_28 = QtWidgets.QLabel(parent=self.roomFrame2_8)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_12.addWidget(self.label_28)
        self.btnPrice2_8 = QtWidgets.QPushButton(parent=self.roomFrame2_8)
        self.btnPrice2_8.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_8.setObjectName("btnPrice2_8")
        self.horizontalLayout_12.addWidget(self.btnPrice2_8)
        self.gridLayout.addWidget(self.roomFrame2_8, 10, 1, 1, 1)
        self.roomFrame2_5 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_5.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_5.setObjectName("roomFrame2_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.roomFrame2_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.roomTextCol2_5 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_5.setObjectName("roomTextCol2_5")
        self.horizontalLayout_7.addLayout(self.roomTextCol2_5)
        self.textEdit_7 = QtWidgets.QTextEdit(parent=self.roomFrame2_5)
        self.textEdit_7.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_7.setObjectName("textEdit_7")
        self.horizontalLayout_7.addWidget(self.textEdit_7)
        self.label_23 = QtWidgets.QLabel(parent=self.roomFrame2_5)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_7.addWidget(self.label_23)
        self.btnPrice2_5 = QtWidgets.QPushButton(parent=self.roomFrame2_5)
        self.btnPrice2_5.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_5.setObjectName("btnPrice2_5")
        self.horizontalLayout_7.addWidget(self.btnPrice2_5)
        self.gridLayout.addWidget(self.roomFrame2_5, 5, 1, 1, 1)
        self.roomFrame2_3 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_3.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_3.setObjectName("roomFrame2_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.roomFrame2_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.roomTextCol2_3 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_3.setObjectName("roomTextCol2_3")
        self.horizontalLayout_6.addLayout(self.roomTextCol2_3)
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.roomFrame2_3)
        self.textEdit_5.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_6.addWidget(self.textEdit_5)
        self.label_22 = QtWidgets.QLabel(parent=self.roomFrame2_3)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.btnPrice2_3 = QtWidgets.QPushButton(parent=self.roomFrame2_3)
        self.btnPrice2_3.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_3.setObjectName("btnPrice2_3")
        self.horizontalLayout_6.addWidget(self.btnPrice2_3)
        self.gridLayout.addWidget(self.roomFrame2_3, 4, 1, 1, 1)
        self.roomFrame2_4 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_4.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_4.setObjectName("roomFrame2_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.roomFrame2_4)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.roomTextCol2_4 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_4.setObjectName("roomTextCol2_4")
        self.horizontalLayout_13.addLayout(self.roomTextCol2_4)
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.roomFrame2_4)
        self.textEdit_6.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_13.addWidget(self.textEdit_6)
        self.label_29 = QtWidgets.QLabel(parent=self.roomFrame2_4)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_13.addWidget(self.label_29)
        self.btnPrice2_4 = QtWidgets.QPushButton(parent=self.roomFrame2_4)
        self.btnPrice2_4.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_4.setObjectName("btnPrice2_4")
        self.horizontalLayout_13.addWidget(self.btnPrice2_4)
        self.gridLayout.addWidget(self.roomFrame2_4, 11, 1, 1, 1)
        self.roomFrame2_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_2.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_2.setObjectName("roomFrame2_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.roomFrame2_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.roomTextCol2_2 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_2.setObjectName("roomTextCol2_2")
        self.horizontalLayout_2.addLayout(self.roomTextCol2_2)
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.roomFrame2_2)
        self.textEdit_4.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_2.addWidget(self.textEdit_4)
        self.label_19 = QtWidgets.QLabel(parent=self.roomFrame2_2)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_2.addWidget(self.label_19)
        self.btnPrice2_2 = QtWidgets.QPushButton(parent=self.roomFrame2_2)
        self.btnPrice2_2.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_2.setObjectName("btnPrice2_2")
        self.horizontalLayout_2.addWidget(self.btnPrice2_2)
        self.gridLayout.addWidget(self.roomFrame2_2, 1, 1, 1, 1)
        self.roomFrame2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2.setObjectName("roomFrame2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.roomFrame2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.roomTextCol2 = QtWidgets.QVBoxLayout()
        self.roomTextCol2.setObjectName("roomTextCol2")
        self.horizontalLayout_3.addLayout(self.roomTextCol2)
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.roomFrame2)
        self.textEdit_3.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout_3.addWidget(self.textEdit_3)
        self.label_18 = QtWidgets.QLabel(parent=self.roomFrame2)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_3.addWidget(self.label_18)
        self.btnPrice2 = QtWidgets.QPushButton(parent=self.roomFrame2)
        self.btnPrice2.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2.setObjectName("btnPrice2")
        self.horizontalLayout_3.addWidget(self.btnPrice2)
        self.gridLayout.addWidget(self.roomFrame2, 0, 1, 1, 1)
        self.roomFrame2_9 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_9.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_9.setObjectName("roomFrame2_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.roomFrame2_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.roomTextCol2_9 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_9.setObjectName("roomTextCol2_9")
        self.horizontalLayout_11.addLayout(self.roomTextCol2_9)
        self.textEdit_11 = QtWidgets.QTextEdit(parent=self.roomFrame2_9)
        self.textEdit_11.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_11.setObjectName("textEdit_11")
        self.horizontalLayout_11.addWidget(self.textEdit_11)
        self.label_27 = QtWidgets.QLabel(parent=self.roomFrame2_9)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_11.addWidget(self.label_27)
        self.btnPrice2_9 = QtWidgets.QPushButton(parent=self.roomFrame2_9)
        self.btnPrice2_9.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_9.setObjectName("btnPrice2_9")
        self.horizontalLayout_11.addWidget(self.btnPrice2_9)
        self.gridLayout.addWidget(self.roomFrame2_9, 9, 1, 1, 1)
        self.roomFrame2_10 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_10.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_10.setObjectName("roomFrame2_10")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.roomFrame2_10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.roomTextCol2_10 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_10.setObjectName("roomTextCol2_10")
        self.horizontalLayout_10.addLayout(self.roomTextCol2_10)
        self.textEdit_12 = QtWidgets.QTextEdit(parent=self.roomFrame2_10)
        self.textEdit_12.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_12.setObjectName("textEdit_12")
        self.horizontalLayout_10.addWidget(self.textEdit_12)
        self.label_26 = QtWidgets.QLabel(parent=self.roomFrame2_10)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_10.addWidget(self.label_26)
        self.btnPrice2_10 = QtWidgets.QPushButton(parent=self.roomFrame2_10)
        self.btnPrice2_10.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_10.setObjectName("btnPrice2_10")
        self.horizontalLayout_10.addWidget(self.btnPrice2_10)
        self.gridLayout.addWidget(self.roomFrame2_10, 8, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_2.setMinimumSize(QtCore.QSize(100, 100))
        self.label_2.setStyleSheet("image: url(:/newPrefix/img/Superior room.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.roomFrame2_7 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_7.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_7.setObjectName("roomFrame2_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.roomFrame2_7)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.roomTextCol2_7 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_7.setObjectName("roomTextCol2_7")
        self.horizontalLayout_4.addLayout(self.roomTextCol2_7)
        self.textEdit_9 = QtWidgets.QTextEdit(parent=self.roomFrame2_7)
        self.textEdit_9.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_9.setObjectName("textEdit_9")
        self.horizontalLayout_4.addWidget(self.textEdit_9)
        self.label_20 = QtWidgets.QLabel(parent=self.roomFrame2_7)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_4.addWidget(self.label_20)
        self.btnPrice2_7 = QtWidgets.QPushButton(parent=self.roomFrame2_7)
        self.btnPrice2_7.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_7.setObjectName("btnPrice2_7")
        self.horizontalLayout_4.addWidget(self.btnPrice2_7)
        self.gridLayout.addWidget(self.roomFrame2_7, 2, 1, 1, 1)
        self.roomFrame2_6 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_6.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_6.setObjectName("roomFrame2_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.roomFrame2_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.roomTextCol2_6 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_6.setObjectName("roomTextCol2_6")
        self.horizontalLayout_5.addLayout(self.roomTextCol2_6)
        self.textEdit_8 = QtWidgets.QTextEdit(parent=self.roomFrame2_6)
        self.textEdit_8.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_5.addWidget(self.textEdit_8)
        self.label_21 = QtWidgets.QLabel(parent=self.roomFrame2_6)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.btnPrice2_6 = QtWidgets.QPushButton(parent=self.roomFrame2_6)
        self.btnPrice2_6.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_6.setObjectName("btnPrice2_6")
        self.horizontalLayout_5.addWidget(self.btnPrice2_6)
        self.gridLayout.addWidget(self.roomFrame2_6, 3, 1, 1, 1)
        self.roomFrame2_12 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.roomFrame2_12.setStyleSheet("\n"
"                QFrame { background-color: rgb(231,228,176); border: 2px solid rgb(184,182,139); border-radius: 6px; padding: 8px; }\n"
"                QLabel#roomTitle2 { font-weight: bold; font-size: 12pt; }\n"
"                QLabel#roomDesc2 { font-size: 9pt; }\n"
"              ")
        self.roomFrame2_12.setObjectName("roomFrame2_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.roomFrame2_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.roomTextCol2_16 = QtWidgets.QVBoxLayout()
        self.roomTextCol2_16.setObjectName("roomTextCol2_16")
        self.horizontalLayout_8.addLayout(self.roomTextCol2_16)
        self.textEdit_18 = QtWidgets.QTextEdit(parent=self.roomFrame2_12)
        self.textEdit_18.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.textEdit_18.setObjectName("textEdit_18")
        self.horizontalLayout_8.addWidget(self.textEdit_18)
        self.label_24 = QtWidgets.QLabel(parent=self.roomFrame2_12)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("background-color: rgb(209, 209, 156);")
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.btnPrice2_16 = QtWidgets.QPushButton(parent=self.roomFrame2_12)
        self.btnPrice2_16.setStyleSheet(" color: rgb(0, 0, 0); background-color: rgb(174,167,126)\n"
" ")
        self.btnPrice2_16.setObjectName("btnPrice2_16")
        self.horizontalLayout_8.addWidget(self.btnPrice2_16)
        self.gridLayout.addWidget(self.roomFrame2_12, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_3.setStyleSheet("image: url(:/newPrefix/img/Deluxe room.jpg);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_4.setStyleSheet("image: url(:/newPrefix/img/Deluxe room.jpg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_5.setStyleSheet("image: url(:/newPrefix/img/Twin room.jpg);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_6.setStyleSheet("image: url(:/newPrefix/img/Twin room.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_7.setStyleSheet("image: url(:/newPrefix/img/Family room.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_8.setStyleSheet("image: url(:/newPrefix/img/Family room.jpg);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_10.setStyleSheet("image: url(:/newPrefix/img/Executive room.jpg);\n"
"")
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_11.setStyleSheet("image: url(:/newPrefix/img/Presidential room.jpg);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_12.setStyleSheet("image: url(:/newPrefix/img/Presidential room.jpg);")
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label_9.setStyleSheet("image: url(:/newPrefix/img/Executive room.jpg);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        self.label.setMinimumSize(QtCore.QSize(150, 100))
        self.label.setStyleSheet("image: url(:/newPrefix/img/Superior room.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.scrollAreaRooms.setWidget(self.scrollAreaWidgetContents)
        self.layoutRoomButtons.addWidget(self.scrollAreaRooms)
        self.layoutRoomsMain.addLayout(self.layoutRoomButtons)
        self.tabAdmin.addTab(self.tabRooms, "")
        self.tabBooking = QtWidgets.QWidget()
        self.tabBooking.setObjectName("tabBooking")
        self.layoutBooking = QtWidgets.QVBoxLayout(self.tabBooking)
        self.layoutBooking.setObjectName("layoutBooking")
        self.layoutButtonsBooking = QtWidgets.QHBoxLayout()
        self.layoutButtonsBooking.setObjectName("layoutButtonsBooking")
        self.tableBooking = QtWidgets.QTableWidget(parent=self.tabBooking)
        self.tableBooking.setStyleSheet("QWidget {\n"
"    width: 29px; /* Atur lebar menjadi 200 piksel */\n"
"}")
        self.tableBooking.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableBooking.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableBooking.setRowCount(0)
        self.tableBooking.setColumnCount(6)
        self.tableBooking.setObjectName("tableBooking")
        item = QtWidgets.QTableWidgetItem()
        self.tableBooking.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooking.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooking.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooking.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooking.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooking.setHorizontalHeaderItem(5, item)
        self.layoutButtonsBooking.addWidget(self.tableBooking)
        self.layoutBooking.addLayout(self.layoutButtonsBooking)
        self.tabAdmin.addTab(self.tabBooking, "")
        self.tabPayments = QtWidgets.QWidget()
        self.tabPayments.setObjectName("tabPayments")
        self.layoutPayments = QtWidgets.QVBoxLayout(self.tabPayments)
        self.layoutPayments.setObjectName("layoutPayments")
        self.tablePayments = QtWidgets.QTableWidget(parent=self.tabPayments)
        self.tablePayments.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tablePayments.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tablePayments.setObjectName("tablePayments")
        self.tablePayments.setColumnCount(4)
        self.tablePayments.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablePayments.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePayments.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePayments.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePayments.setHorizontalHeaderItem(3, item)
        self.layoutPayments.addWidget(self.tablePayments)
        self.layoutButtonsPayments = QtWidgets.QHBoxLayout()
        self.layoutButtonsPayments.setObjectName("layoutButtonsPayments")
        self.layoutPayments.addLayout(self.layoutButtonsPayments)
        self.tabAdmin.addTab(self.tabPayments, "")
        self.tabUsers = QtWidgets.QWidget()
        self.tabUsers.setObjectName("tabUsers")
        self.layoutUsers = QtWidgets.QVBoxLayout(self.tabUsers)
        self.layoutUsers.setObjectName("layoutUsers")
        self.label_30 = QtWidgets.QLabel(parent=self.tabUsers)
        self.label_30.setMaximumSize(QtCore.QSize(50, 50))
        self.label_30.setStyleSheet("background-color: #fff;\n"
"border: 2px solid #8A2BE2;\n"
"border-radius: 15px;\n"
"padding: 8px;\n"
"")
        self.label_30.setObjectName("label_30")
        self.layoutUsers.addWidget(self.label_30)
        self.label_13 = QtWidgets.QLabel(parent=self.tabUsers)
        self.label_13.setObjectName("label_13")
        self.layoutUsers.addWidget(self.label_13)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.tabUsers)
        self.lineEdit.setObjectName("lineEdit")
        self.layoutUsers.addWidget(self.lineEdit)
        self.label_14 = QtWidgets.QLabel(parent=self.tabUsers)
        self.label_14.setObjectName("label_14")
        self.layoutUsers.addWidget(self.label_14)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.tabUsers)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.layoutUsers.addWidget(self.lineEdit_2)
        self.label_15 = QtWidgets.QLabel(parent=self.tabUsers)
        self.label_15.setObjectName("label_15")
        self.layoutUsers.addWidget(self.label_15)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.tabUsers)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.layoutUsers.addWidget(self.lineEdit_3)
        self.label_16 = QtWidgets.QLabel(parent=self.tabUsers)
        self.label_16.setObjectName("label_16")
        self.layoutUsers.addWidget(self.label_16)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.tabUsers)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.layoutUsers.addWidget(self.lineEdit_4)
        self.label_17 = QtWidgets.QLabel(parent=self.tabUsers)
        self.label_17.setObjectName("label_17")
        self.layoutUsers.addWidget(self.label_17)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.tabUsers)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.layoutUsers.addWidget(self.lineEdit_5)
        self.layoutButtonsUsers = QtWidgets.QHBoxLayout()
        self.layoutButtonsUsers.setObjectName("layoutButtonsUsers")
        self.btnDeleteUser = QtWidgets.QPushButton(parent=self.tabUsers)
        self.btnDeleteUser.setStyleSheet("background-color: rgb(190,60,60);")
        self.btnDeleteUser.setObjectName("btnDeleteUser")
        self.layoutButtonsUsers.addWidget(self.btnDeleteUser)
        self.btnAddUser = QtWidgets.QPushButton(parent=self.tabUsers)
        self.btnAddUser.setStyleSheet("background-color: rgb(80,160,80);")
        self.btnAddUser.setObjectName("btnAddUser")
        self.layoutButtonsUsers.addWidget(self.btnAddUser)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.layoutButtonsUsers.addItem(spacerItem)
        self.layoutUsers.addLayout(self.layoutButtonsUsers)
        self.tabAdmin.addTab(self.tabUsers, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_31 = QtWidgets.QLabel(parent=self.tab)
        self.label_31.setGeometry(QtCore.QRect(-30, 10, 841, 461))
        self.label_31.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(parent=self.tab)
        self.label_32.setGeometry(QtCore.QRect(220, 55, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("background-color: rgb(207, 207, 154);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.tab)
        self.label_33.setGeometry(QtCore.QRect(130, 190, 551, 191))
        self.label_33.setStyleSheet("background-color: rgb(229, 229, 171);")
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.tab)
        self.label_34.setGeometry(QtCore.QRect(370, 120, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(parent=self.tab)
        self.label_35.setGeometry(QtCore.QRect(320, 260, 161, 41))
        self.label_35.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_35.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_35.setObjectName("label_35")
        self.tabAdmin.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabAdmin)

        self.retranslateUi(DashboardAdmin)
        self.tabAdmin.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(DashboardAdmin)

    def retranslateUi(self, DashboardAdmin):
        _translate = QtCore.QCoreApplication.translate
        DashboardAdmin.setWindowTitle(_translate("DashboardAdmin", "Dashboard Admin Penginapan"))
        self.lblTitle.setText(_translate("DashboardAdmin", "                                🏨 Selamat Datang di Hotel Pandawa 🏨"))
        self.tabAdmin.setWhatsThis(_translate("DashboardAdmin", "<html><head/><body><p>Upload Pembayaran</p></body></html>"))
        self.textEdit_13.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Family</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🍱 Termasuk Sarapan 🍱</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">28 m² / 301 ft², kasur king + single, TV, AC, WiFi, sofa kecil, kamar mandi luas, sarapan 3 tamu</span></p></body></html>"))
        self.label_25.setText(_translate("DashboardAdmin", "Rp.750.000"))
        self.btnPrice2_11.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_10.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Presidential</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">50 m² / 538 ft², kasur king premium, ruang tamu, ruang makan, mini bar lengkap, WiFi cepat, kamar mandi bathtub</span></p></body></html>"))
        self.label_28.setText(_translate("DashboardAdmin", "Rp.2.800.000"))
        self.btnPrice2_8.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_7.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Twin</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🍱 Termasuk Sarapan 🍱</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">20 m² / 215 ft², 2 kasur single, AC, WiFi, meja kecil, sarapan 2 tamu</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_23.setText(_translate("DashboardAdmin", "Rp.500.000"))
        self.btnPrice2_5.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_5.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Twin</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">20 m² / 215 ft², 2 kasur single, AC, WiFi, meja kecil</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_22.setText(_translate("DashboardAdmin", "Rp.450.000"))
        self.btnPrice2_3.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_6.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Presidential</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🍱 Termasuk Sarapan 🍱</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">50 m² / 538 ft², kasur king premium, ruang tamu, ruang makan, mini bar lengkap, WiFi cepat, kamar mandi bathtub, sarapan 2 tamu</span></p></body></html>"))
        self.label_29.setText(_translate("DashboardAdmin", "Rp.2.950.000"))
        self.btnPrice2_4.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_4.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Superior</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🍱 <span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">Termasuk sarapan </span>🍱</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">18 m² / 194 ft², 1 kasur queen, AC, WiFi, pemandangan kota, sarapan 2 tamu</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_19.setText(_translate("DashboardAdmin", "Rp.400.000"))
        self.btnPrice2_2.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_3.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Superior</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">18 m² / 194 ft², 1 kasur queen, AC, WIFI, pemandangan kota</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_18.setText(_translate("DashboardAdmin", "Rp.350.000"))
        self.btnPrice2.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_11.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Executive</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🍱 Termasuk Sarapan 🍱</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">26 m² / 280 ft², kasur king, meja kerja, WiFi, kamar mandi luas, sarapan 2 tamu</span></p></body></html>"))
        self.label_27.setText(_translate("DashboardAdmin", "Rp.650.000"))
        self.btnPrice2_9.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_12.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Executive</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">26 m² / 280 ft², kasur king, meja kerja, WiFi, kamar mandi luas</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_26.setText(_translate("DashboardAdmin", "Rp.600.000"))
        self.btnPrice2_10.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_9.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Deluxe</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">22 m² / 237 ft², kasur queen/king, AC, WiFi, area duduk</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_20.setText(_translate("DashboardAdmin", "Rp.500.000"))
        self.btnPrice2_7.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_8.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Deluxe</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">🍱 Termasuk Sarapan 🍱</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">22 m² / 237 ft², kasur queen/king, AC, WiFi, area duduk, sarapan 2 tamu</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_21.setText(_translate("DashboardAdmin", "Rp.550.000"))
        self.btnPrice2_6.setText(_translate("DashboardAdmin", "Pesan"))
        self.textEdit_18.setHtml(_translate("DashboardAdmin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Family</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:600;\">Room</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:600;\">Fasilitas Utama: </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt;\">28 m² / 301 ft², kasur king + single, TV, AC, WiFi, sofa kecil, kamar mandi luas</span></p></body></html>"))
        self.label_24.setText(_translate("DashboardAdmin", "Rp.700.000"))
        self.btnPrice2_16.setText(_translate("DashboardAdmin", "Pesan"))
        self.tabAdmin.setTabText(self.tabAdmin.indexOf(self.tabRooms), _translate("DashboardAdmin", "Daftar Kamar"))
        item = self.tableBooking.horizontalHeaderItem(0)
        item.setText(_translate("DashboardAdmin", "ID Booking"))
        item = self.tableBooking.horizontalHeaderItem(1)
        item.setText(_translate("DashboardAdmin", "Tgl. Booking"))
        item = self.tableBooking.horizontalHeaderItem(2)
        item.setText(_translate("DashboardAdmin", "Tipe Kamar"))
        item = self.tableBooking.horizontalHeaderItem(3)
        item.setText(_translate("DashboardAdmin", "Jumlah Kamar"))
        item = self.tableBooking.horizontalHeaderItem(4)
        item.setText(_translate("DashboardAdmin", "Check-in"))
        item = self.tableBooking.horizontalHeaderItem(5)
        item.setText(_translate("DashboardAdmin", "Check-out"))
        self.tabAdmin.setTabText(self.tabAdmin.indexOf(self.tabBooking), _translate("DashboardAdmin", "Riwayat Kamar"))
        item = self.tablePayments.horizontalHeaderItem(0)
        item.setText(_translate("DashboardAdmin", "ID Pembayaran"))
        item = self.tablePayments.horizontalHeaderItem(1)
        item.setText(_translate("DashboardAdmin", "Tgl. Bayar"))
        item = self.tablePayments.horizontalHeaderItem(2)
        item.setText(_translate("DashboardAdmin", "Total Bayar"))
        item = self.tablePayments.horizontalHeaderItem(3)
        item.setText(_translate("DashboardAdmin", "Metode"))
        self.tabAdmin.setTabText(self.tabAdmin.indexOf(self.tabPayments), _translate("DashboardAdmin", "Riwayat Pembayaran"))
        self.label_30.setText(_translate("DashboardAdmin", "Foto Profil"))
        self.label_13.setText(_translate("DashboardAdmin", "Nama Lengkap "))
        self.label_14.setText(_translate("DashboardAdmin", "Email"))
        self.label_15.setText(_translate("DashboardAdmin", "No. Telpon"))
        self.label_16.setText(_translate("DashboardAdmin", "Username"))
        self.label_17.setText(_translate("DashboardAdmin", "Password"))
        self.btnDeleteUser.setText(_translate("DashboardAdmin", "Logout"))
        self.btnAddUser.setText(_translate("DashboardAdmin", "Simpan Perubahan"))
        self.tabAdmin.setTabText(self.tabAdmin.indexOf(self.tabUsers), _translate("DashboardAdmin", "Profil Saya"))
        self.label_32.setText(_translate("DashboardAdmin", "          Upload Bukti Pembayaran"))
        self.label_34.setText(_translate("DashboardAdmin", "⬇️"))
        self.label_35.setText(_translate("DashboardAdmin", "Upload bukti transfer disini"))
        self.tabAdmin.setTabText(self.tabAdmin.indexOf(self.tab), _translate("DashboardAdmin", "Unggah Bukti"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DashboardAdmin = QtWidgets.QWidget()
    ui = Ui_DashboardAdmin()
    ui.setupUi(DashboardAdmin)
    DashboardAdmin.show()
    sys.exit(app.exec())
