# Form implementation generated from reading ui file 'popup_pembayarann.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pembayaran(object):
    def setupUi(self, Pembayaran):
        Pembayaran.setObjectName("Pembayaran")
        Pembayaran.resize(543, 405)
        self.verticalLayout = QtWidgets.QVBoxLayout(Pembayaran)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=Pembayaran)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("background-color: rgb(191, 191, 142);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout.addWidget(self.labelTitle)
        self.btnCash = QtWidgets.QPushButton(parent=Pembayaran)
        self.btnCash.setStyleSheet("background-color: rgb(238, 238, 177);\n"
"color: rgb(70, 141, 211);")
        self.btnCash.setObjectName("btnCash")
        self.verticalLayout.addWidget(self.btnCash)
        self.btnQRIS = QtWidgets.QPushButton(parent=Pembayaran)
        self.btnQRIS.setStyleSheet("background-color: rgb(238, 238, 177);\n"
"color: rgb(0, 0, 255);")
        self.btnQRIS.setObjectName("btnQRIS")
        self.verticalLayout.addWidget(self.btnQRIS)
        self.btnDebit = QtWidgets.QPushButton(parent=Pembayaran)
        self.btnDebit.setStyleSheet("background-color: rgb(238, 238, 177);\n"
"color: rgb(255, 0, 0);")
        self.btnDebit.setObjectName("btnDebit")
        self.verticalLayout.addWidget(self.btnDebit)
        self.btnKembali = QtWidgets.QPushButton(parent=Pembayaran)
        self.btnKembali.setStyleSheet("\n"
"background-color: rgb(172, 172, 128);")
        self.btnKembali.setObjectName("btnKembali")
        self.verticalLayout.addWidget(self.btnKembali)

        self.retranslateUi(Pembayaran)
        QtCore.QMetaObject.connectSlotsByName(Pembayaran)

    def retranslateUi(self, Pembayaran):
        _translate = QtCore.QCoreApplication.translate
        Pembayaran.setWindowTitle(_translate("Pembayaran", "Metode Pembayaran"))
        self.labelTitle.setText(_translate("Pembayaran", "Pilih Metode Pembayaran"))
        self.btnCash.setText(_translate("Pembayaran", "DANA"))
        self.btnQRIS.setText(_translate("Pembayaran", "BRI"))
        self.btnDebit.setText(_translate("Pembayaran", "Jatim"))
        self.btnKembali.setText(_translate("Pembayaran", "Kembali"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pembayaran = QtWidgets.QWidget()
    ui = Ui_Pembayaran()
    ui.setupUi(Pembayaran)
    Pembayaran.show()
    sys.exit(app.exec())
