# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterForm(object):
    def setupUi(self, RegisterForm):
        RegisterForm.setObjectName("RegisterForm")
        RegisterForm.resize(393, 567)
        RegisterForm.setStyleSheet("    QWidget {\n"
"        background-color: rgb(255, 244, 185);\n"
"    }\n"
"    QFrame {\n"
"        background-color: rgb(174, 167, 126);\n"
"        border-radius: 15px;\n"
"        padding: 20px;\n"
"    }\n"
"    QLabel {\n"
"        font-size: 10pt;\n"
"        color: rgb(0, 0, 0);\n"
"    }\n"
"    QLineEdit {\n"
"        background-color: rgb(255, 255, 255);\n"
"        border: 1px solid #b0b0b0;\n"
"        border-radius: 8px;\n"
"        padding: 6px;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: rgb(255, 244, 185);\n"
"        border-radius: 8px;\n"
"        padding: 8px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(153, 136, 101);\n"
"        color: white;\n"
"    }")
        self.verticalLayout = QtWidgets.QVBoxLayout(RegisterForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(parent=RegisterForm)
        self.lblTitle.setStyleSheet("font-size: 18pt; font-weight: bold; color: rgb(116, 80, 66); ")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.frameForm = QtWidgets.QFrame(parent=RegisterForm)
        self.frameForm.setStyleSheet("\n"
"        QFrame {\n"
"          background-color: rgb(174, 167, 126);\n"
"            border-radius: 15px;\n"
"            padding: 20px;\n"
"        }\n"
"        QLabel {\n"
"            font-size: 10pt;\n"
"        }\n"
"        QLineEdit {\n"
"            border: 1px solid #b0b0b0;\n"
"            border-radius: 5px;\n"
"            padding: 6px;\n"
"        }\n"
"        QPushButton {\n"
"            background-color: rgb(255, 244, 185);\n"
"            border-radius: 8px;\n"
"            padding: 8px;\n"
"        }\n"
"        QPushButton:hover {\n"
"            background-color: rgb(153, 136, 101);\n"
"          color: white;\n"
"        }\n"
"      ")
        self.frameForm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frameForm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frameForm.setObjectName("frameForm")
        self.formLayout = QtWidgets.QFormLayout(self.frameForm)
        self.formLayout.setObjectName("formLayout")
        self.lblUsername = QtWidgets.QLabel(parent=self.frameForm)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(parent=self.frameForm)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUsername)
        self.lblPassword = QtWidgets.QLabel(parent=self.frameForm)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(parent=self.frameForm)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtPassword)
        self.lblNama = QtWidgets.QLabel(parent=self.frameForm)
        self.lblNama.setObjectName("lblNama")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblNama)
        self.txtNama = QtWidgets.QLineEdit(parent=self.frameForm)
        self.txtNama.setObjectName("txtNama")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNama)
        self.lblEmail = QtWidgets.QLabel(parent=self.frameForm)
        self.lblEmail.setObjectName("lblEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblEmail)
        self.txtEmail = QtWidgets.QLineEdit(parent=self.frameForm)
        self.txtEmail.setObjectName("txtEmail")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtEmail)
        self.lblWA = QtWidgets.QLabel(parent=self.frameForm)
        self.lblWA.setObjectName("lblWA")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lblWA)
        self.txtWA = QtWidgets.QLineEdit(parent=self.frameForm)
        self.txtWA.setObjectName("txtWA")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtWA)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnRegister = QtWidgets.QPushButton(parent=self.frameForm)
        self.btnRegister.setObjectName("btnRegister")
        self.buttonLayout.addWidget(self.btnRegister)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.buttonLayout)
        self.lblStatus = QtWidgets.QLabel(parent=self.frameForm)
        self.lblStatus.setStyleSheet("")
        self.lblStatus.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblStatus.setObjectName("lblStatus")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lblStatus)
        self.verticalLayout.addWidget(self.frameForm)

        self.retranslateUi(RegisterForm)
        QtCore.QMetaObject.connectSlotsByName(RegisterForm)

    def retranslateUi(self, RegisterForm):
        _translate = QtCore.QCoreApplication.translate
        RegisterForm.setWindowTitle(_translate("RegisterForm", "Form Registrasi Penginapan"))
        self.lblTitle.setText(_translate("RegisterForm", "🏨 Registrasi Penginapan 🏨"))
        self.lblUsername.setText(_translate("RegisterForm", "Username:"))
        self.lblPassword.setText(_translate("RegisterForm", "Password:"))
        self.lblNama.setText(_translate("RegisterForm", "Nama Lengkap:"))
        self.lblEmail.setText(_translate("RegisterForm", "Email:"))
        self.lblWA.setText(_translate("RegisterForm", "No WhatsApp:"))
        self.btnRegister.setText(_translate("RegisterForm", "Daftar"))
        self.lblStatus.setText(_translate("RegisterForm", "Sudah punya akun? Login sekarang"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterForm = QtWidgets.QWidget()
    ui = Ui_RegisterForm()
    ui.setupUi(RegisterForm)
    RegisterForm.show()
    sys.exit(app.exec())
