# Form implementation generated from reading ui file 'tampilan_awal.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_WelcomeForm(object):
    def setupUi(self, WelcomeForm):
        WelcomeForm.setObjectName("WelcomeForm")
        WelcomeForm.resize(400, 420)
        WelcomeForm.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: rgb(255, 244, 185);\n"
"    }\n"
"    QFrame {\n"
"        background-color: rgb(174, 167, 126);\n"
"        border-radius: 15px;\n"
"        padding: 20px;\n"
"    }\n"
"    QLabel {\n"
"        font-size: 10pt;\n"
"        color: rgb(0, 0, 0);\n"
"    }\n"
"    QPushButton {\n"
"        background-color: rgb(255, 244, 185);\n"
"        border-radius: 8px;\n"
"        padding: 8px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(153, 136, 101);\n"
"        color: white;\n"
"    }\n"
"   ")
        self.mainLayout = QtWidgets.QVBoxLayout(WelcomeForm)
        self.mainLayout.setObjectName("mainLayout")
        self.lblTitle = QtWidgets.QLabel(parent=WelcomeForm)
        self.lblTitle.setStyleSheet("font-size: 18pt; font-weight: bold; color: rgb(116, 80, 66); margin-top: 20px;")
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.mainLayout.addWidget(self.lblTitle)
        self.frameWelcome = QtWidgets.QFrame(parent=WelcomeForm)
        self.frameWelcome.setObjectName("frameWelcome")
        self.layoutButtons = QtWidgets.QVBoxLayout(self.frameWelcome)
        self.layoutButtons.setSpacing(15)
        self.layoutButtons.setObjectName("layoutButtons")
        self.lblDesc = QtWidgets.QLabel(parent=self.frameWelcome)
        self.lblDesc.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblDesc.setObjectName("lblDesc")
        self.layoutButtons.addWidget(self.lblDesc)
        self.btnLogin = QtWidgets.QPushButton(parent=self.frameWelcome)
        self.btnLogin.setObjectName("btnLogin")
        self.layoutButtons.addWidget(self.btnLogin)
        self.btnRegister = QtWidgets.QPushButton(parent=self.frameWelcome)
        self.btnRegister.setObjectName("btnRegister")
        self.layoutButtons.addWidget(self.btnRegister)
        self.mainLayout.addWidget(self.frameWelcome)

        self.retranslateUi(WelcomeForm)
        QtCore.QMetaObject.connectSlotsByName(WelcomeForm)

    def retranslateUi(self, WelcomeForm):
        _translate = QtCore.QCoreApplication.translate
        WelcomeForm.setWindowTitle(_translate("WelcomeForm", "Selamat Datang"))
        self.lblTitle.setText(_translate("WelcomeForm", "🏨 Selamat Datang 🏨"))
        self.lblDesc.setText(_translate("WelcomeForm", "Silakan masuk untuk melanjutkan:"))
        self.btnLogin.setText(_translate("WelcomeForm", "Login"))
        self.btnRegister.setText(_translate("WelcomeForm", "Register"))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeForm = QtWidgets.QWidget()
    ui = Ui_WelcomeForm()
    ui.setupUi(WelcomeForm)
    WelcomeForm.show()
    sys.exit(app.exec())
