# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hapus_rating.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetHapusRating(object):
    def setupUi(self, WidgetHapusRating):
        WidgetHapusRating.setObjectName("WidgetHapusRating")
        WidgetHapusRating.resize(1050, 650)
        WidgetHapusRating.setStyleSheet("QWidget { background-color: rgb(231,228,176); }\n"
"QFrame#frameHeader { background-color: white; border-radius: 5px; padding: 10px; border: 1px solid #8b5e3c; }\n"
"QLabel { color:#3e2a16; }\n"
"QTableWidget { background: white; gridline-color: #8b5e3c; }\n"
"QHeaderView::section { background-color: #8b5e3c; color: white; padding: 5px; }")
        self.gridLayout = QtWidgets.QGridLayout(WidgetHapusRating)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(WidgetHapusRating)
        self.pushButton.setStyleSheet("background-color: rgb(135, 69, 38);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.tableRating = QtWidgets.QTableWidget(WidgetHapusRating)
        self.tableRating.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableRating.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableRating.setRowCount(0)
        self.tableRating.setColumnCount(6)
        self.tableRating.setObjectName("tableRating")
        item = QtWidgets.QTableWidgetItem()
        self.tableRating.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRating.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRating.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRating.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRating.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableRating.setHorizontalHeaderItem(5, item)
        self.tableRating.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableRating, 1, 0, 1, 2)
        self.frameHeader = QtWidgets.QFrame(WidgetHapusRating)
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.gridLayoutHeader = QtWidgets.QGridLayout(self.frameHeader)
        self.gridLayoutHeader.setObjectName("gridLayoutHeader")
        self.lblTitle = QtWidgets.QLabel(self.frameHeader)
        self.lblTitle.setStyleSheet("font-size: 16pt; font-weight: bold;\n"
"background-color: rgb(255, 255, 255);")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayoutHeader.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameHeader, 0, 0, 1, 2)

        self.retranslateUi(WidgetHapusRating)
        QtCore.QMetaObject.connectSlotsByName(WidgetHapusRating)

    def retranslateUi(self, WidgetHapusRating):
        _translate = QtCore.QCoreApplication.translate
        WidgetHapusRating.setWindowTitle(_translate("WidgetHapusRating", "Admin - Hapus Rating/Ulasan"))
        self.pushButton.setText(_translate("WidgetHapusRating", "Kembali"))
        item = self.tableRating.horizontalHeaderItem(0)
        item.setText(_translate("WidgetHapusRating", "Nama Pengguna"))
        item = self.tableRating.horizontalHeaderItem(1)
        item.setText(_translate("WidgetHapusRating", "Nama Kamar"))
        item = self.tableRating.horizontalHeaderItem(2)
        item.setText(_translate("WidgetHapusRating", "Rating"))
        item = self.tableRating.horizontalHeaderItem(3)
        item.setText(_translate("WidgetHapusRating", "Tanggal"))
        item = self.tableRating.horizontalHeaderItem(4)
        item.setText(_translate("WidgetHapusRating", "Komentar"))
        item = self.tableRating.horizontalHeaderItem(5)
        item.setText(_translate("WidgetHapusRating", "Aksi"))
        self.lblTitle.setText(_translate("WidgetHapusRating", "⭐ Daftar Rating dan Komentar Pengguna"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetHapusRating = QtWidgets.QWidget()
    ui = Ui_WidgetHapusRating()
    ui.setupUi(WidgetHapusRating)
    WidgetHapusRating.show()
    sys.exit(app.exec_())
