# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hapus_kritik.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetKritikSaran(object):
    def setupUi(self, WidgetKritikSaran):
        WidgetKritikSaran.setObjectName("WidgetKritikSaran")
        WidgetKritikSaran.resize(1000, 650)
        WidgetKritikSaran.setStyleSheet("QWidget { background-color: rgb(231,228,176); }\n"
"QFrame#frameHeader { background-color: white; border-radius: 5px; padding: 10px; border: 1px solid #8b5e3c; }\n"
"QLabel { color:#3e2a16; }\n"
"QTableWidget { background: white; gridline-color: #8b5e3c; }\n"
"QHeaderView::section { background-color: #8b5e3c; color: white; padding: 5px; }")
        self.gridLayout = QtWidgets.QGridLayout(WidgetKritikSaran)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(WidgetKritikSaran)
        self.pushButton.setStyleSheet("background-color: rgb(135, 69, 38);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.tableKritik = QtWidgets.QTableWidget(WidgetKritikSaran)
        self.tableKritik.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableKritik.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableKritik.setRowCount(0)
        self.tableKritik.setColumnCount(6)
        self.tableKritik.setObjectName("tableKritik")
        item = QtWidgets.QTableWidgetItem()
        self.tableKritik.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableKritik.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableKritik.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableKritik.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableKritik.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableKritik.setHorizontalHeaderItem(5, item)
        self.tableKritik.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableKritik, 1, 0, 1, 2)
        self.frameHeader = QtWidgets.QFrame(WidgetKritikSaran)
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.gridLayoutHeader = QtWidgets.QGridLayout(self.frameHeader)
        self.gridLayoutHeader.setObjectName("gridLayoutHeader")
        self.lblTitle = QtWidgets.QLabel(self.frameHeader)
        self.lblTitle.setStyleSheet("font-size: 16pt; font-weight: bold;\n"
"background-color: rgb(255, 255, 255);")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayoutHeader.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameHeader, 0, 0, 1, 2)

        self.retranslateUi(WidgetKritikSaran)
        QtCore.QMetaObject.connectSlotsByName(WidgetKritikSaran)

    def retranslateUi(self, WidgetKritikSaran):
        _translate = QtCore.QCoreApplication.translate
        WidgetKritikSaran.setWindowTitle(_translate("WidgetKritikSaran", "Admin - Kritik dan Saran"))
        self.pushButton.setText(_translate("WidgetKritikSaran", "Kembali"))
        item = self.tableKritik.horizontalHeaderItem(0)
        item.setText(_translate("WidgetKritikSaran", "ID Kritik"))
        item = self.tableKritik.horizontalHeaderItem(1)
        item.setText(_translate("WidgetKritikSaran", "Tanggal"))
        item = self.tableKritik.horizontalHeaderItem(2)
        item.setText(_translate("WidgetKritikSaran", "User"))
        item = self.tableKritik.horizontalHeaderItem(3)
        item.setText(_translate("WidgetKritikSaran", "Kritik/Saran"))
        item = self.tableKritik.horizontalHeaderItem(4)
        item.setText(_translate("WidgetKritikSaran", "Status"))
        item = self.tableKritik.horizontalHeaderItem(5)
        item.setText(_translate("WidgetKritikSaran", "Aksi"))
        self.lblTitle.setText(_translate("WidgetKritikSaran", "📧 Daftar Kritik dan Saran Pengguna"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetKritikSaran = QtWidgets.QWidget()
    ui = Ui_WidgetKritikSaran()
    ui.setupUi(WidgetKritikSaran)
    WidgetKritikSaran.show()
    sys.exit(app.exec_())
