# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'konfirmasi_pembayaran.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WidgetDataTransfer(object):
    def setupUi(self, WidgetDataTransfer):
        WidgetDataTransfer.setObjectName("WidgetDataTransfer")
        WidgetDataTransfer.resize(950, 650)
        WidgetDataTransfer.setStyleSheet("QWidget { background-color: rgb(231,228,176); }\n"
"QFrame#frameHeader { background-color: white; border-radius: 5px; padding: 10px; border: 1px solid #8b5e3c; }\n"
"QLabel { color:#3e2a16; }\n"
"QTableWidget { background: white; gridline-color: #8b5e3c; }\n"
"QHeaderView::section { background-color: #8b5e3c; color: white; padding: 5px; }")
        self.gridLayout = QtWidgets.QGridLayout(WidgetDataTransfer)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(WidgetDataTransfer)
        self.pushButton.setStyleSheet("background-color: rgb(135, 69, 38);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.tableTransferData = QtWidgets.QTableWidget(WidgetDataTransfer)
        self.tableTransferData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableTransferData.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableTransferData.setRowCount(0)
        self.tableTransferData.setColumnCount(5)
        self.tableTransferData.setObjectName("tableTransferData")
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTransferData.setHorizontalHeaderItem(4, item)
        self.tableTransferData.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableTransferData, 1, 0, 1, 2)
        self.frameHeader = QtWidgets.QFrame(WidgetDataTransfer)
        self.frameHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeader.setObjectName("frameHeader")
        self.gridLayoutHeader = QtWidgets.QGridLayout(self.frameHeader)
        self.gridLayoutHeader.setObjectName("gridLayoutHeader")
        self.lblTitle = QtWidgets.QLabel(self.frameHeader)
        self.lblTitle.setStyleSheet("font-size: 16pt; font-weight: bold;\n"
"background-color: rgb(255, 255, 255);")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.gridLayoutHeader.addWidget(self.lblTitle, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frameHeader, 0, 0, 1, 2)

        self.retranslateUi(WidgetDataTransfer)
        QtCore.QMetaObject.connectSlotsByName(WidgetDataTransfer)

    def retranslateUi(self, WidgetDataTransfer):
        _translate = QtCore.QCoreApplication.translate
        WidgetDataTransfer.setWindowTitle(_translate("WidgetDataTransfer", "Data Transfer Admin"))
        self.pushButton.setText(_translate("WidgetDataTransfer", "Kembali"))
        item = self.tableTransferData.horizontalHeaderItem(0)
        item.setText(_translate("WidgetDataTransfer", "ID Bayar"))
        item = self.tableTransferData.horizontalHeaderItem(1)
        item.setText(_translate("WidgetDataTransfer", "Nama Pengirim"))
        item = self.tableTransferData.horizontalHeaderItem(2)
        item.setText(_translate("WidgetDataTransfer", "Total Bayar"))
        item = self.tableTransferData.horizontalHeaderItem(3)
        item.setText(_translate("WidgetDataTransfer", "Status"))
        item = self.tableTransferData.horizontalHeaderItem(4)
        item.setText(_translate("WidgetDataTransfer", "Aksi"))
        self.lblTitle.setText(_translate("WidgetDataTransfer", "💰 Konfirmasi Pembayaran"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WidgetDataTransfer = QtWidgets.QWidget()
    ui = Ui_WidgetDataTransfer()
    ui.setupUi(WidgetDataTransfer)
    WidgetDataTransfer.show()
    sys.exit(app.exec_())
