# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lihat_rating.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogDetailUlasan(object):
    def setupUi(self, DialogDetailUlasan):
        DialogDetailUlasan.setObjectName("DialogDetailUlasan")
        DialogDetailUlasan.resize(850, 600)
        DialogDetailUlasan.setStyleSheet("QDialog { background-color: rgb(231,228,176); }\n"
"QFrame#frameHeaderDetail { background-color: white; border-radius: 5px; padding: 10px; border: 1px solid #8b5e3c; }\n"
"QLabel { color:#3e2a16; }\n"
"QTableWidget { background: white; gridline-color: #8b5e3c; }\n"
"QHeaderView::section { background-color: #8b5e3c; color: white; padding: 5px; }\n"
"QPushButton { background-color:#8b5e3c; color:white; border-radius:4px; padding:6px; }")
        self.gridLayout = QtWidgets.QGridLayout(DialogDetailUlasan)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(DialogDetailUlasan)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.tableUlasanDetail = QtWidgets.QTableWidget(DialogDetailUlasan)
        self.tableUlasanDetail.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableUlasanDetail.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableUlasanDetail.setColumnCount(5)
        self.tableUlasanDetail.setObjectName("tableUlasanDetail")
        self.tableUlasanDetail.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableUlasanDetail.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUlasanDetail.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUlasanDetail.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUlasanDetail.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUlasanDetail.setHorizontalHeaderItem(4, item)
        self.tableUlasanDetail.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.tableUlasanDetail, 2, 0, 1, 2)
        self.frameHeaderDetail = QtWidgets.QFrame(DialogDetailUlasan)
        self.frameHeaderDetail.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameHeaderDetail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHeaderDetail.setObjectName("frameHeaderDetail")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frameHeaderDetail)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblNamaKamar = QtWidgets.QLabel(self.frameHeaderDetail)
        self.lblNamaKamar.setStyleSheet("font-size: 16pt; font-weight: bold;")
        self.lblNamaKamar.setObjectName("lblNamaKamar")
        self.gridLayout_2.addWidget(self.lblNamaKamar, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.frameHeaderDetail, 0, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(DialogDetailUlasan)
        self.label_3.setStyleSheet("font-size: 10pt; font-weight: bold; margin-top: 10px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)

        self.retranslateUi(DialogDetailUlasan)
        QtCore.QMetaObject.connectSlotsByName(DialogDetailUlasan)

    def retranslateUi(self, DialogDetailUlasan):
        _translate = QtCore.QCoreApplication.translate
        DialogDetailUlasan.setWindowTitle(_translate("DialogDetailUlasan", "Detail Ulasan Kamar"))
        self.pushButton.setText(_translate("DialogDetailUlasan", "Kembali"))
        item = self.tableUlasanDetail.horizontalHeaderItem(0)
        item.setText(_translate("DialogDetailUlasan", "Nama Pengguna"))
        item = self.tableUlasanDetail.horizontalHeaderItem(1)
        item.setText(_translate("DialogDetailUlasan", "Nama Kamar"))
        item = self.tableUlasanDetail.horizontalHeaderItem(2)
        item.setText(_translate("DialogDetailUlasan", "Rating"))
        item = self.tableUlasanDetail.horizontalHeaderItem(3)
        item.setText(_translate("DialogDetailUlasan", "Tanggal"))
        item = self.tableUlasanDetail.horizontalHeaderItem(4)
        item.setText(_translate("DialogDetailUlasan", "Komentar"))
        self.lblNamaKamar.setText(_translate("DialogDetailUlasan", "Rating Penginapan Pandawa"))
        self.label_3.setText(_translate("DialogDetailUlasan", "Daftar Ulasan Individual:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogDetailUlasan = QtWidgets.QDialog()
    ui = Ui_DialogDetailUlasan()
    ui.setupUi(DialogDetailUlasan)
    DialogDetailUlasan.show()
    sys.exit(app.exec_())
