# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(400, 350)
        LoginForm.setStyleSheet("\n"
"    QWidget {\n"
"        background-color: rgb(255, 244, 185);\n"
"    }\n"
"    QFrame {\n"
"        background-color: rgb(174, 167, 126);\n"
"        border-radius: 15px;\n"
"        padding: 20px;\n"
"    }\n"
"    QLabel {\n"
"        font-size: 10pt;\n"
"        color: rgb(0, 0, 0);\n"
"    }\n"
"    QLineEdit {\n"
"        background-color: rgb(255, 255, 255);\n"
"        border: 1px solid #b0b0b0;\n"
"        border-radius: 8px;\n"
"        padding: 6px;\n"
"    }\n"
"    QPushButton {\n"
"        background-color: rgb(255, 244, 185);\n"
"        border-radius: 8px;\n"
"        padding: 8px;\n"
"        font-weight: bold;\n"
"    }\n"
"    QPushButton:hover {\n"
"        background-color: rgb(153, 136, 101);\n"
"        color: white;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(LoginForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblTitle = QtWidgets.QLabel(LoginForm)
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setStyleSheet("font-size: 18pt; font-weight: bold; color: rgb(116, 80, 66); margin-top: 20px;")
        self.lblTitle.setObjectName("lblTitle")
        self.verticalLayout.addWidget(self.lblTitle)
        self.frameLogin = QtWidgets.QFrame(LoginForm)
        self.frameLogin.setObjectName("frameLogin")
        self.formLayout = QtWidgets.QFormLayout(self.frameLogin)
        self.formLayout.setObjectName("formLayout")
        self.lblUsername = QtWidgets.QLabel(self.frameLogin)
        self.lblUsername.setObjectName("lblUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lblUsername)
        self.txtUsername = QtWidgets.QLineEdit(self.frameLogin)
        self.txtUsername.setObjectName("txtUsername")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txtUsername)
        self.lblPassword = QtWidgets.QLabel(self.frameLogin)
        self.lblPassword.setObjectName("lblPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lblPassword)
        self.txtPassword = QtWidgets.QLineEdit(self.frameLogin)
        self.txtPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword.setObjectName("txtPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txtPassword)
        self.btnLogin = QtWidgets.QPushButton(self.frameLogin)
        self.btnLogin.setObjectName("btnLogin")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.btnLogin)
        self.lblFooter = QtWidgets.QLabel(self.frameLogin)
        self.lblFooter.setAlignment(QtCore.Qt.AlignCenter)
        self.lblFooter.setStyleSheet("font-size: 9pt; color: rgb(50, 50, 50); margin-top: 10px;")
        self.lblFooter.setObjectName("lblFooter")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.lblFooter)
        self.verticalLayout.addWidget(self.frameLogin)
        self.verticalLayout.setStretch(1, 1)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Login Penginapan"))
        self.lblTitle.setText(_translate("LoginForm", "🏨 Login Penginapan 🏨"))
        self.lblUsername.setText(_translate("LoginForm", "Username:"))
        self.txtUsername.setPlaceholderText(_translate("LoginForm", "Masukkan username..."))
        self.lblPassword.setText(_translate("LoginForm", "Password:"))
        self.txtPassword.setPlaceholderText(_translate("LoginForm", "Masukkan password..."))
        self.btnLogin.setText(_translate("LoginForm", "Login"))
        self.lblFooter.setText(_translate("LoginForm", "Belum punya akun? Daftar di resepsionis"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginForm = QtWidgets.QWidget()
    ui = Ui_LoginForm()
    ui.setupUi(LoginForm)
    LoginForm.show()
    sys.exit(app.exec_())
